# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
    parallelism: 1
    working_directory: ~/repo
    docker:
        - image: circleci/node:12.18.2
release: &release
    steps:
        - checkout
        - attach_workspace:
              at: ~/repo
        - run:
              name: Release npm package
              command: npx semantic-release

jobs:
    setup:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  key: v4-yarn-{{ checksum "yarn.lock" }}
            - run:
                  name: Install front-end dependencies
                  command: yarn --frozen-lockfile --ignore-engines --ignore-scripts
            - save_cache:
                  key: v4-yarn-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - node_modules

    check_commit_message:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Define environment variable with lastest commit's message
                  command: |
                      echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
                      source $BASH_ENV
            - run:
                  name: Lint commit message
                  command: echo "$COMMIT_MESSAGE" | npx commitlint

    check_code:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Stylelint check
                  command: npx stylelint "src/{*,**/*,**/**/*}.{css,scss}" --allow-empty-input
            - run:
                  name: Prettier formatting check
                  command: npx prettier "src/{*,**/*,**/**/*}.{css,scss}" --check

    release_to_github:
        <<: *defaults
        <<: *release

    release_to_npm:
        <<: *defaults
        <<: *release

workflows:
    version: 2
    check_and_release_workflow:
        jobs:
            - setup
            - check_commit_message:
                  requires:
                      - setup
            - check_code:
                  requires:
                      - check_commit_message
            - release_to_github:
                  context: github-deploy
                  requires:
                      - check_code
                  filters:
                      branches:
                          only:
                              - next
            - release_to_npm:
                  context: npm-deploy
                  requires:
                      - check_code
                  filters:
                      branches:
                          only:
                              - master
