name: "Lint PR"

on:
    pull_request:
        branches: [master, next]
    pull_request_target:
        branches: [master, next]
        types:
            - opened
            - edited
            - synchronize

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    main:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v4.5.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
